<?php
require_once 'RomaClient.php';

/**
 * Test class for RomaClient.
 * Generated by PHPUnit on 2010-08-05 at 16:37:31.
 */
class RomaClientJointTest0 extends PHPUnit_Framework_TestCase
{
  protected $server_script_path = '../../roma_root/roma.bash';

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   *
   * @access protected
   */
  protected function setUp(){

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   *
   * @access protected
   */
  protected function tearDown(){

  }

  /**
   * No.1
   * No.
   */
  public function testConfMiss() {
    print "\n***TEST*** ". get_class($this) ."::". __FUNCTION__ . "\n";
    exec($this->server_script_path . ' starts');
    sleep(15);
    $roma_client = RomaClient::getInstance(array("-d", "localhost_11211", "localhost_11212"));
    for ($i = 0; $i < 100; $i++) {
      $ret = $roma_client->set("test-conf-miss-".$i, "test-conf-miss-".$i, 1000);
    }
    exec($this->server_script_path . ' stops');
    $this->assertTrue($ret);
  }
}
?>
