<?php
require_once 'RomaClient.php';

/**
 * Test class for RomaClient.
 * Generated by PHPUnit on 2010-08-05 at 16:37:31.
 */
class RomaClientJointTest21 extends PHPUnit_Framework_TestCase
{

  //protected $roma_client;
  protected $server_script_path = '../../roma_root/roma.bash';

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   *
   * @access protected
   */
  protected function setUp(){
    //$this->roma_client = RomaClient::getInstance(array("localhost_11211","localhost_11212"));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   *
   * @access protected
   */
  protected function tearDown(){
    exec($this->server_script_path . ' stops');
  }

  /**
   * No.59
   * No.
   */
  public function testRomaStartConnect() {
    print "\n***TEST*** ". get_class($this) ."::". __FUNCTION__ . "\n";
    $flg = False;
    for ($i = 0; $i < 50000; $i++) {
      print '.';
      if ($i == 10) {
        exec($this->server_script_path.' starts');
      }
      $roma_client = RomaClient::getInstance(array("localhost_11211", "localhost_11212"));
      if ($roma_client != False) {
        break;
      }
    }
    sleep(20);
    $this->assertInstanceOf(RomaClient, $roma_client);
  }
}
?>
